require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NflGamesController do

  # This should return the minimal set of attributes required to create a valid
  # NflGame. As you add validations to NflGame, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NflGamesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all nfl_games as @nfl_games" do
      nfl_game = NflGame.create! valid_attributes
      get :index, {}, valid_session
      assigns(:nfl_games).should eq([nfl_game])
    end
  end

  describe "GET show" do
    it "assigns the requested nfl_game as @nfl_game" do
      nfl_game = NflGame.create! valid_attributes
      get :show, {:id => nfl_game.to_param}, valid_session
      assigns(:nfl_game).should eq(nfl_game)
    end
  end

  describe "GET new" do
    it "assigns a new nfl_game as @nfl_game" do
      get :new, {}, valid_session
      assigns(:nfl_game).should be_a_new(NflGame)
    end
  end

  describe "GET edit" do
    it "assigns the requested nfl_game as @nfl_game" do
      nfl_game = NflGame.create! valid_attributes
      get :edit, {:id => nfl_game.to_param}, valid_session
      assigns(:nfl_game).should eq(nfl_game)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NflGame" do
        expect {
          post :create, {:nfl_game => valid_attributes}, valid_session
        }.to change(NflGame, :count).by(1)
      end

      it "assigns a newly created nfl_game as @nfl_game" do
        post :create, {:nfl_game => valid_attributes}, valid_session
        assigns(:nfl_game).should be_a(NflGame)
        assigns(:nfl_game).should be_persisted
      end

      it "redirects to the created nfl_game" do
        post :create, {:nfl_game => valid_attributes}, valid_session
        response.should redirect_to(NflGame.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nfl_game as @nfl_game" do
        # Trigger the behavior that occurs when invalid params are submitted
        NflGame.any_instance.stub(:save).and_return(false)
        post :create, {:nfl_game => {}}, valid_session
        assigns(:nfl_game).should be_a_new(NflGame)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NflGame.any_instance.stub(:save).and_return(false)
        post :create, {:nfl_game => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nfl_game" do
        nfl_game = NflGame.create! valid_attributes
        # Assuming there are no other nfl_games in the database, this
        # specifies that the NflGame created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NflGame.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => nfl_game.to_param, :nfl_game => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested nfl_game as @nfl_game" do
        nfl_game = NflGame.create! valid_attributes
        put :update, {:id => nfl_game.to_param, :nfl_game => valid_attributes}, valid_session
        assigns(:nfl_game).should eq(nfl_game)
      end

      it "redirects to the nfl_game" do
        nfl_game = NflGame.create! valid_attributes
        put :update, {:id => nfl_game.to_param, :nfl_game => valid_attributes}, valid_session
        response.should redirect_to(nfl_game)
      end
    end

    describe "with invalid params" do
      it "assigns the nfl_game as @nfl_game" do
        nfl_game = NflGame.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NflGame.any_instance.stub(:save).and_return(false)
        put :update, {:id => nfl_game.to_param, :nfl_game => {}}, valid_session
        assigns(:nfl_game).should eq(nfl_game)
      end

      it "re-renders the 'edit' template" do
        nfl_game = NflGame.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NflGame.any_instance.stub(:save).and_return(false)
        put :update, {:id => nfl_game.to_param, :nfl_game => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nfl_game" do
      nfl_game = NflGame.create! valid_attributes
      expect {
        delete :destroy, {:id => nfl_game.to_param}, valid_session
      }.to change(NflGame, :count).by(-1)
    end

    it "redirects to the nfl_games list" do
      nfl_game = NflGame.create! valid_attributes
      delete :destroy, {:id => nfl_game.to_param}, valid_session
      response.should redirect_to(nfl_games_url)
    end
  end

end
